
macros = Hash.new
macros[:unicode]     = "̣\\\\[0-9a-f]{1,6}(?:\\r\\n|[ \\n\\r\\t\\f])?"
macros[:escape]      = "(?:#{macros[:unicode]}|\\\\[^\\n\\r\\f0-9a-f])"
macros[:nonascii]    = "[^\\0-\\237]"
macros[:nmstart]     = "(?:[_a-z]|#{macros[:nonascii]}|#{macros[:escape]})"
macros[:nmchar]      = "(?:[_a-z0-9\\-]|#{macros[:nonascii]}|#{macros[:escape]}"
macros[:ident]       = "[-]?#{macros["nmstart"]}#{macros["nmchar"]}*"
macros[:num]         = "(?:[0-9]+|[0-9]*\\.[0-9]+)"
  macros[:nl]          = "(?:\n|\r\n|\r|\f)"
macros[:string1]     = "\\\"([^\n\r\f\\\"]|\\#{matches[:nl]}|#{matches[:escape]})*\\\""
macros[:string2]     = "\\'([^\n\r\f\\']|\\#{matches[:nl]}|#{matches[:escape]})*\\'"
macros[:string]      = "(?:#{matches[:string1]}|#{matches[:string2]})"
macros[:badstring1]  = "\\\"([^\n\r\f\\\"]|\\#{matches[:nl]}|#{matches[:escape]})*\\?"
macros[:badstring2]  = "\\'([^\n\r\f\\']|\\#{matches[:nl]}|#{matches[:escape]})*\\?"
macros[:badstring]   = "(?:#{matches[:badstring1]}|#{matches[:badstring2]})"
macros[:badcomment1] = "\\/\\*[^*]*\\*+([^/*][^*]*\\*+)*"
macros[:badcomment2] = "\\/\\*[^*]*(\\*+[^/*][^*]*)*"
macros[:badcomment]  = "(?:#{matches[:badcomment1]}|#{matches[:badcomment2]})"
macros[:w]           = "[ \t\r\n\f]*"
macros[:baduri1]     = "url\\(#{matches[:w]}(?:[!#\$%&*-~]|#{matches[:nonascii]}|#{matches[:escape]})*#{matches[:w]}"
macros[:baduri2]     = "url\\(#{matches[:w]}#{matches[:string]}#{matches[:w]}"
macros[:baduri3]     = "url\\(#{matches[:w]}#{matches[:badstring]}"
macros[:baduri]      = "(?:#{matches[:baduri1]}|#{matches[:baduri2]}|#{matches[:baduri3]})"

tokens = Hash.new
tokens[:INDENT]      = /#{macros[:indent]}/
tokens[:ATKEYWORD]   = /@#{macros[:indent]}/
tokens[:STRING]      = /#{macros[:string]}/
tokens[:BAD_STRING]  = /#{macros[:badstring]}/
tokens[:BAD_URI]     = /#{macros[:baduri]}/
tokens[:BAD_COMMENT] = /#{macros[:badcomment]}/
tokens[:HASH]        = /##{macros[:name]}/
tokens[:NUMBER]      = /#{macros[:num]}/
tokens[:PERCENTAGE]  = /#{macros[:num]}%/
tokens[:DIMENSION]   = /#{macros[:num]}#{macros[:ident]}/
tokens[:URI]         = /(?:url\(#{macros[:w]}#{macros[:string]}#{macros[:w]}\)|url\(#{macros[:w]}(?:[!#$%&*-\[\]-~]|#{macros[:nonascii]}|#{macros[:escape]})*#{macros[:w]}\))/
tokens[:UNICODE]     = /u\+[0-9a-f?]{1,6}(?:-[0-9a-f]{1,6})?/
tokens[:CDO]         = /<!--/
tokens[:CDC]         = /-->/
tokens[:COLON]       = /:/
tokens[:SEMICOLON]   = /;/
tokens[:OP_CURLY]    = /\{/
tokens[:CL_CURLY]    = /\}/
tokens[:OP_BRACKETS] = /\(/
tokens[:CL_BRACKETS] = /\)/
tokens[:OP_SQUARE]   = /\[/
tokens[:CL_SQUARE]   = /\]/
tokens[:S]           = /[ \t\r\n\f]+/
tokens[:COMMENT]     = /\/\*[^*]*\*+([^/*][^*]*\*+)*\//
tokens[:FUNCTION]    = /#{macros[:ident]}\(/
tokens[:INCLUDES]    = /~=/
tokens[:DASHMATCH]   = /\|=/
