#!/usr/bin/env ruby

require 'parser.rb'

# enougth arguments given
if ARGV.empty?
  puts "USAGE: padding0 [file] ..."
else 
  file = ARGV[0]
  if File.exist?(file)
    # read the file and parse it using the Parser class
    data = IO.read(file)
    puts data
    Parser.new(data)
  else
    pits "File #{file} does not exist!"
  end
end
